version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DB_HOST=mysql
      - DB_NAME=transcript_cleaner
      - DB_USER=flask_user
      - DB_PASSWORD=${DB_PASSWORD}
      # APIキーはシステム環境変数から取得
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=transcript_cleaner
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:
  uploads:

networks:
  app-network:
    driver: bridge